config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :lists, only: [:index, :new, :create, :show, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: :destroy
  # get '/lists', to: 'lists#index'

  # get '/lists/new', to: 'lists#new'
  # post '/lists', to: 'lists#create'

  # # get 'lists/:id/bookmarks/new', to

  # get '/lists/:id', to: 'lists#show', as: 'list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  # has_many :lists, through: :bookmarks

  validates :overview, :title, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    # @movie = Movie.find(params[:movie_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= link_to "Back to the list", list_path(@list) %>
<hr>
<div class="container">
  <h2>Add a movie to your <strong><em><%= @list.name %></em></strong> list</h2>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, collection: Movie.all %>
    <%= f.input :comment %>
    <%= f.submit "Add movie", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= link_to "Create a new list 🛠", new_list_path %>
<hr>
<h1>All your Lists:</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<%= link_to "Back to all lists", lists_path %>
<hr>
<div class="container">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name, :placeholder => 'How do you want to call your new list?'%>
    <%= f.button :submit, class: "btn-primary" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<%= link_to "Back to all lists", lists_path %>
<%= link_to "Delete this list",
  list_path(@list),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<hr>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h2>You are inside the <strong><em><%= @list.name %></em></strong> list</h2>
      <ul>
        <% @list.bookmarks.each do |bookmark| %>
        <li><strong>Movie: </strong><%= bookmark.movie.title %></li>
        <p><strong>Your comment: </strong><%= bookmark.comment %></p>
        <% end %>
      </ul>
      <div><%= link_to "Add a movie", new_list_bookmark_path(@list) %></div>
    </div>
  </div>
</div>